#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Language Package for Fanseline Image Toolbox

lang_cn_s = {
    "mainWindowName": "帆室邻图像工具箱",
    "Computing": " - 处理中",
    "Compare": "对比原图",
    "Show Mask": "显示选区",
    "Color Range": "色彩范围选取",
    "Grabcut": "内容识别选取",
    "Magic Wand": "魔棒选取",
    "Select Tools": "普通选取",
    "Adjust Selection": "调整总选区",
    "Deselect All": "清空总选区",
    "Select Inverse": "全部反选",
    "Test": "测试按钮",
    "Undo Mask": "撤销选区",
    "Redo Mask": "重做选区",
    "Create Local Mask": "新建局部选区",
    "Adjust Global Mask": "调整总选区",
    "Dehair": "蜜蜡滤镜",
    "Adjust Color": "调整颜色",
    "Inpaint": "修复画笔",
    "Smooth Skin": "磨皮滤镜",
    "Glow Blur": "辉光模糊",
    "Load Image": "打开图片",
    "Save Image": "保存图片",
    "Undo": "撤销",
    "Redo": "重做",
    "Filters": "滤镜组",
    "Save & Load": "保存与读取",
    "Select an Image": "请选择一张图片",
    "Image File Sets": "图片文件 (*.jpg;*.png;*.bmp);;JPEG 文件 (*.jpg);;PNG 文件 (*.png);;BMP 文件 (*.bmp)",
    "Notice": "通知",
    "OK": "确定",
    "Read File Error": "读取文件错误",
    "not supported": "该文件不受支持。",
    "Be Patient": "大尺寸图片将会导致操作卡顿！",
    "Large Image Notice": "您尝试打开的图片尺寸非常大……\n\n请问您要将图片缩小到 3264x短边 吗？",
    "JPG File": "JPG 文件",
    "Save Comparison": "保存对比图",
    "Save Comparison (Vertical)": "上下对比",
    "Save Comparison (Horizontal)": "左右对比",
    "JPG Quality": "JPG 质量",
    "Save as JPG": "保存为 JPG",
    "PNG File": "PNG 文件",
    "BMP File": "BMP 文件",
    "Cancel": "取消",
    "Other Formats": "其它格式",
    "ROI Select": "框选目标",
    "Add(+)": "增选(+)",
    "Subtract(-)": "减选(-)",
    "Grab Cut Iteration": "算法迭代次数",
    "Brush Size": "笔刷尺寸",
    "Grow": "扩张选区",
    "Contract": "收缩选区",
    "Feather": "羽化边缘",
    "1. Frame Select": "1. 框选物体",
    "2. Mark Manually": "2. 手动标记",
    "3. Edit Selection Edge": "3. 编辑选区边缘",
    "Replace All": "替换总选区",
    "Add to(+)": "加入总选区(+)",
    "Subtract from(-)": "从总选区减去(-)",
    "Apply to Main Mask": "应用到总选区",
    "Upper Difference": "上容差",
    "Lower Difference": "下容差",
    "Magic Wand Select": "魔棒选取",
    "Edit Selection Edge": "编辑选区边缘",
    "H Tolerance": "H 容差",
    "S Tolerance": "S 容差",
    "V Tolerance": "V 容差",
    "Soft Select": "软选择",
    "Manual Select": "手动选取颜色",
    "Otsu-Cr": "大津分割",
    "HSV Auto": "HSV 自动",
    "YCrCb Auto": "YCrCb 自动",
    "Auto Select": "自动选取皮肤",
    "Brush": "选区笔工具",
    "Rectangle": "方形工具",
    "Ellipse": "椭圆工具",
    "Lasso": "套索工具",
    "Edit Current Selection": "编辑当前选区",
    "Edit Main Selection": "编辑总选区",
    "Opacity": "不透明度",
    "Apply": "应用",
    "Brightness": "亮度",
    "Contrast": "对比度",
    "Saturation": "饱和度",
    "Highlight": "高光",
    "Shadow": "阴影",
    "Warm Color": "暖色调",
    "Magenta Tone": "洋红色调",
    "Basic Adjust": "基础调整",
    "Color Adjust": "颜色调整",
    "Reset": "重置",
    "Apply to Image": "应用到图像",
    "Median K-Size": "中值核大小",
    "Dark Lower": "暗线下阈值",
    "Dark Upper": "暗线上阈值",
    "Bright Lower": "亮线下阈值",
    "Bright Upper": "亮线上阈值",
    "Main Parameter": "主参数",
    "Thresholds": "压制阈值",
    "Telea": "Telea",
    "Navier-Stokes": "Navier-Stokes",
    "Search Radius": "搜索半径",
    "Inpaint Method": "修复算法",
    "Compute Range": "计算范围",
    "Strength": "强度",
    "Blur Diameter": "模糊直径",
    "Whiten": "增白",
    "Skin Smooth": "磨皮",
    "Blend": "渲染",
    "Glow Effect": "辉光效果",
    "Blur Effect": "模糊效果",
    "Glow": "辉光",
    "JPG Files (*.jpg)": "JPG 文件 (*.jpg)",
    "PNG Files (*.png)": "PNG 文件 (*.png)",
    "BMP Files (*.bmp)": "BMP 文件 (*.bmp)",
    "Save as PNG": "保存为 PNG",
    "Save as BMP": "保存为 BMP",
    "Soft Transition": "软过渡",
    "Classic Filters": "经典滤镜",
    "Kernel Size": "滤波器核大小",
    "Sigma-Color": "颜色标准差",
    "Sigma-Space": "空间标准差",
    "Sigma": "标准差",
    "Sharpen": "锐化",
    "Pixelation": "马赛克",
    "Bilateral Simple": "简易双边滤波",
    "Bilateral Full": "双边滤波",
    "Median Filter": "中值滤波",
    "Gaussian Filter": "高斯滤波",
    "Box Filter": "方形滤波",
    "Simple Sharpen": "简易锐化",
    "Vignette": "晕影效果",
    "Tools": "工具",
    "NO": "否",
    "YES": "是",
    "Opening a new image...": "正在打开图片……",
    "Would you like to discard": "您要放弃当前的编辑吗？",
    "Quitting...": "退出软件……",
    "Welcome!": "欢迎使用!",
    "Switch View": "切换视图",
    "Save Masked Image as PNG": "保存选区图像\n(保存为PNG)",
    "File Save Error": "文件保存出错",
    "Unable to save this image!": "无法保存该图片！",
    "File Saved": "文件已保存",
    "Your image has been saved.": "您的图片已保存",
    "Save Masked Image": "保存选区图像",
    "Help": "帮助",
    "Luminance Denoise": "亮度降噪",
    "Color Denoise": "颜色降噪",
    "Denoise (Slow)": "降噪(处理缓慢)",
    "Select a Filter": "选择一个滤镜",
    "Settings & Help": "设置和帮助",
    "Max Undo Steps": "最大撤销步数",
    "Steps": "步数",
    "About": "关于",
    "Take Effect After Restart": "*重启软件后生效",
    "Help document not found": "帮助文件未找到！",

}

lang_en = {
    "mainWindowName": "Fanseline Image Toolbox",
    "Computing": " - Computing",
    "Compare": "Compare",
    "Show Mask": "Show Mask",
    "Color Range": "Color Range",
    "Grabcut": "Grabcut",
    "Magic Wand": "Magic Wand",
    "Select Tools": "Select Tools",
    "Adjust Selection": "Adjust Selection",
    "Deselect All": "Deselect All",
    "Select Inverse": "Select Inverse",
    "Test": "Test",
    "Undo Mask": "Undo Mask",
    "Redo Mask": "Redo Mask",
    "Create Local Mask": "Create Local Mask",
    "Adjust Global Mask": "Adjust Global Mask",
    "Dehair": "Beeswax",
    "Adjust Color": "Adjust Color",
    "Inpaint": "Inpaint",
    "Smooth Skin": "Smooth Skin",
    "Glow Blur": "Glow Blur",
    "Load Image": "Load Image",
    "Save Image": "Save Image",
    "Undo": "Undo",
    "Redo": "Redo",
    "Filters": "Filters",
    "Save & Load": "Save & Load",
    "Select an Image": "Select an Image",
    "Image File Sets": "Image Files (*.jpg;*.png;*.bmp);;JPEG Files (*.jpg);;PNG Files (*.png);;BMP Files (*.bmp)",
    "Notice": "Notice",
    "OK": "OK",
    "Read File Error": "Read File Error",
    "not supported": "This file is not supported.",
    "Be Patient": "Large image will make your computer laggy!",
    "Large Image Notice": "Your image is very LARGE...\n\nWould you like you resize your image to\n3264 x shortside?",
    "JPG File": "JPG File",
    "Save Comparison": "Save Comparison",
    "Save Comparison (Vertical)": "Vertical",
    "Save Comparison (Horizontal)": "Horizontal",
    "JPG Quality": "JPG Quality",
    "Save as JPG": "Save as JPG",
    "PNG File": "PNG File",
    "BMP File": "BMP File",
    "Cancel": "Cancel",
    "Other Formats": "Other Formats",
    "ROI Select": "ROI Select",
    "Add(+)": "Add(+)",
    "Subtract(-)": "Subtract(-)",
    "Grab Cut Iteration": "Grabcut Iteration",
    "Brush Size": "Brush Size",
    "Grow": "Grow",
    "Contract": "Contract",
    "Feather": "Feather Edge",
    "1. Frame Select": "1. Frame Select",
    "2. Mark Manually": "2. Mark Manually",
    "3. Edit Selection Edge": "3. Edit Selection Edge",
    "Replace All": "Replace All",
    "Add to(+)": "Add to(+)",
    "Subtract from(-)": "Subtract from(-)",
    "Apply to Main Mask": "Apply to Main Mask",
    "Upper Difference": "Upper Difference",
    "Lower Difference": "Lower Difference",
    "Magic Wand Select": "Magic Wand Select",
    "Edit Selection Edge": "Edit Selection Edge",
    "H Tolerance": "H Tolerance",
    "S Tolerance": "S Tolerance",
    "V Tolerance": "V Tolerance",
    "Soft Select": "Soft Select",
    "Manual Select": "Manual Select Color",
    "Otsu-Cr": "Otsu-Cr",
    "HSV Auto": "HSV Auto",
    "YCrCb Auto": "YCrCb Auto",
    "Auto Select": "Auto Select Skin",
    "Brush": "Brush",
    "Rectangle": "Rectangle",
    "Ellipse": "Ellipse",
    "Lasso": "Lasso",
    "Edit Current Selection": "Edit Current Selection",
    "Edit Main Selection": "Edit Main Selection",
    "Opacity": "Opacity",
    "Apply": "Apply",
    "Brightness": "Brightness",
    "Contrast": "Contrast",
    "Saturation": "Saturation",
    "Highlight": "Highlight",
    "Shadow": "Shadow",
    "Warm Color": "Warm Color",
    "Magenta Tone": "Magenta Tone",
    "Basic Adjust": "Basic Adjust",
    "Color Adjust": "Color Adjust",
    "Reset": "Reset",
    "Apply to Image": "Apply to Image",
    "Median K-Size": "Median K-Size",
    "Dark Lower": "Dark Lower",
    "Dark Upper": "Dark Upper",
    "Bright Lower": "Bright Lower",
    "Bright Upper": "Bright Upper",
    "Main Parameter": "Main Parameter",
    "Thresholds": "Thresholds",
    "Telea": "Telea",
    "Navier-Stokes": "Navier-Stokes",
    "Search Radius": "Search Radius",
    "Inpaint Method": "Inpaint Method",
    "Compute Range": "Compute Range",
    "Strength": "Strength",
    "Blur Diameter": "Blur Diameter",
    "Whiten": "Whiten",
    "Skin Smooth": "Skin Smooth",
    "Blend": "Blend",
    "Glow Effect": "Glow Effect",
    "Blur Effect": "Blur Effect",
    "Glow": "Glow",
    "JPG Files (*.jpg)": "JPG Files (*.jpg)",
    "PNG Files (*.png)": "PNG Files (*.png)",
    "BMP Files (*.bmp)": "BMP Files (*.bmp)",
    "Save as PNG": "Save as PNG",
    "Save as BMP": "Save as BMP",
    "Soft Transition": "Soft Transition",
    "Classic Filters": "Classic Filters",
    "Kernel Size": "Kernel Size",
    "Sigma-Color": "Sigma-Color",
    "Sigma-Space": "Sigma-Space",
    "Sigma": "Sigma",
    "Sharpen": "Sharpen",
    "Pixelation": "Pixelation",
    "Bilateral Simple": "Bilateral Simple",
    "Bilateral Full": "Bilateral Filter",
    "Median Filter": "Median Filter",
    "Gaussian Filter": "Gaussian Filter",
    "Box Filter": "Box Filter",
    "Simple Sharpen": "Simple Sharpen",
    "Vignette": "Vignette",
    "Tools": "Tools",
    "NO": "NO",
    "YES": "YES",
    "Opening a new image...": "Opening a new image...",
    "Would you like to discard": "Would you like to discard your current work?",
    "Quitting...": "Quitting...",
    "Welcome!": "Welcome!",
    "Switch View": "Switch View",
    "Save Masked Image as PNG": "Save Masked Image\n(as PNG)",
    "File Save Error": "File Save Error",
    "Unable to save this image!": "Unable to save this image!",
    "File Saved": "File Saved",
    "Your image has been saved.": "Your image has been saved.",
    "Save Masked Image": "Save Masked Image",
    "Help": "Help",
    "Luminance Denoise": "Luminance Denoise",
    "Color Denoise": "Color Denoise",
    "Denoise (Slow)": "Denoise (Slow)",
    "Select a Filter": "Select a Filter",
    "Settings & Help": "Settings && Help",
    "Max Undo Steps": "Max Undo Steps",
    "Steps": "Steps",
    "About": "About",
    "Take Effect After Restart": "*Take Effect After Restart",
    "Help document not found": "Help document not found!",
}
